### ISSUE TITLE
I don'get how to use it

### ISSUE THREAD

**Issue by 0xalmanac** [KTibow/lovelace-soft-theme#1]
I simply have no idea how to apply the theme

**Comment by 0xalmanac** [comment]
![image](https://user-images.githubusercontent.com/95438532/147497781-714c82a8-7145-41e7-b4b9-011f6e4706aa.png)

**Comment by 0xalmanac** [comment]
The old `class: soft-ui` seems to have no effect

**Comment by KTibow** [comment]
Did you figure it out?
