### ISSUE TITLE
Icons from picture-elements cards not displayed

### ISSUE THREAD

**Issue by sanderlv** [KTibow/lovelace-soft-theme#2]
When not using a theme (backend-selected) I get this:
![image](https://user-images.githubusercontent.com/16528916/148682944-0bc70ccc-3545-4347-a039-7489835da15d.png)

when using this theme (Soft UI) I get:
![image](https://user-images.githubusercontent.com/16528916/148682953-877ec95e-a603-41db-9e52-1c74dcf795a8.png)

when using this theme (Dark Soft UI) I get:
![image](https://user-images.githubusercontent.com/16528916/148682967-529f3614-8e7f-4ce6-96bf-3c5f5dfd1914.png)

What happens with my icons in the picture-elements card?

**Comment by KTibow** [comment]
Dark Soft UI is out of date, and should be removed from your installation.
As for why they're not blue with Soft, that's just how I created the theme. IMO if something is powered off, it shouldn't be vibrant.
