### ISSUE TITLE
Using the Automatic feature

### ISSUE THREAD

**Issue by Qpernicus** [KTibow/lovelace-soft-theme#3]
Like the look of the theme, and speed compared to the ' old' Soft UI.. but what is controlling the 'automatic' feature for dark and light? 

Because during the day i expected the light theme, but it turns dark.. Am i missing some setting?

**Comment by KTibow** [comment]
Home Assistant controls this now. On desktop, you'll find the manual switch in your user config menu:
![image](https://user-images.githubusercontent.com/10727862/148687646-989f494a-d908-4c2b-8a2a-aaab977bc1b5.png)
You could probably still do the same thing with an automation, given you can force a mode:
![image](https://user-images.githubusercontent.com/10727862/148687670-5e7e5af2-9ce2-41c5-8496-a44fe80eecd8.png)

**Comment by Qpernicus** [comment]
> Home Assistant controls this now. On desktop, you'll find the manual switch in your user config menu:
> 
> ![image](https://user-images.githubusercontent.com/10727862/148687646-989f494a-d908-4c2b-8a2a-aaab977bc1b5.png)
> 
> You could probably still do the same thing with an automation, given you can force a mode:
> 
> ![image](https://user-images.githubusercontent.com/10727862/148687670-5e7e5af2-9ce2-41c5-8496-a44fe80eecd8.png)
> 
> 

Thx

I should look into my system then. Just checked with default. It switches to dark to very early.

**Comment by KTibow** [comment]
Going to close this issue for now, but just tell me if you have any more questions.

**Comment by Qpernicus** [comment]
> Going to close this issue for now, but just tell me if you have any more questions.

Yeah I find it odd, but perhaps it's obvious: it is dark now outside. Autotheme = light theme. Earlier today it was light outside , when set to auto: Dark theme.. That feels the wrong way around... but that is more with HA/system itself than your theme, so it can stay closed.

**Comment by KTibow** [comment]
Auto is based on your system settings for dark mode.
