### ISSUE TITLE
Borders around cards

### ISSUE THREAD

**Issue by molly200** [KTibow/lovelace-soft-theme#4]
Hello,

I using your themes in my home assistant dashboards. With the new changes global changes in HA, the cards now display some unwanted and ugly  borders around them. Is there any work around to make the themes look the same as before? 

Thanks
Mike

**Comment by KTibow** [comment]
oh those
this theme isn't that active anymore but i'll see if i can find any variables that hide them

**Comment by KTibow** [comment]
try this https://gist.github.com/KTibow/ef73547f67c783910e37994f0fef68df

**Comment by molly200** [comment]
Thanks for the feedback!

Yeah, I think I may have addresed this under the wrong project. I am actually using some of the lovelace-light-soft-ui-theme (https://github.com/KTibow/lovelace-light-soft-ui-theme). 

I see that your link has included some short version of both light and dark themes together in one file.

Tried to add this in one of the theme file:
card-mod-root-yaml: |
.: |
  ha-app-layout {
     –ha-card-border-width: 0px;
     –ha-card-border-radius: 0px;
  }

It doesn’t work!

**Comment by KTibow** [comment]
try adding `ha-card-border-width: "0"` toplevel, not in card-mod

**Comment by molly200** [comment]
There is an ha-card-border-width: 3px entry already in the file. Do I add another?

**Comment by molly200** [comment]
Added another line, restarted and it worked. Thank you!
